### PR TITLE
Add screen rotation option for devices with upside down screen. 

### PR DESCRIPTION
**Pull request by ghost**
Environment variable HAL_TRANSFORM_ROT

### CODE REVIEW

**Comment by sledges** [comment]
Where should this env variable be defined for libhybris clients to pick it up?

**Comment by krnlyng** [comment]
@MisterMagisterDev can you change it to HYBRIS_HAL_TRANSFORM_ROT or similar?
@sledges it is only needed by the compositor, so would go to droid-hal-device.conf

**Comment by MisterMagisterDev** [comment]
@krnlyng also i forgot to add header for getenv

**Comment by Michal-Szczepaniak** [comment]
@krnlyng @sledges Is it okay now? Tested it and it compiles now and also checking if it's not null is there.

**Comment by krnlyng** [comment]
@Michal-Szczepaniak LGTM but i wonder if we should do that PR to upstream, @sledges?

**Comment by sledges** [comment]
@krnlyng, yes indeed going through upstream would look much cleaner and the usually preferred way of contributing, thanks @ghost.

**Comment by Michal-Szczepaniak** [comment]
Moved to libhybris/hybris#374

**Pull request closed without merging**
